api:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        # this value can be an absolute path or an absolute URL
        path: '/api'
        permanent: true

authentication_token:
    path: /api/login
    methods: ['POST']