api:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        # this value can be an absolute path or an absolute URL
        path: '/api'
        permanent: true

authentication_token:
    path: /api/login
    methods: ['POST']

meal_like:
    path: /api/meals/like
    methods: ['POST']
    controller: App\Controller\MealController::likeAction

meal_dislike:
    path: /api/meals/dislike
    methods: ['POST']
    controller: App\Controller\MealController::dislikeAction

register:
    path: /api/register
    methods: ['POST']
    controller: App\Controller\UserController::registerAction
